repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests before committing
        entry: bash .hooks/pre-commit.sh
        language: system
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
