repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        entry: bash .hooks/pre-commit.sh
        language: system
        stages: [commit]
      - id: structure
        name: Check structure
        entry: make structure
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]
