repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        entry: bash .hooks/pre-commit.sh
        language: system
        stages: [commit]
      - id: pylint
        name: Run pylint
        entry: pylint ./src
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]
      - id: black
        name: Run black
        entry: black src
        language: system
        types: [python]
        stages: [commit]
